name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Docker image for Vue.js
        run: |
          docker build -t vuejs-frontend -f ./vuejs/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag vuejs-frontend ${{ secrets.DOCKER_USERNAME }}/vuejs-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/vuejs-frontend:latest

  deploy:
    needs: build
    runs-on: [git-runner-fe]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/vuejs-frontend:latest

      - name: Stop existing Vue.js container
        run: |
          docker stop vuejs-frontend || true
          docker rm vuejs-frontend || true

      - name: Run Docker container for Vue.js
        run: |
          docker run -d -p 80:80 --name vuejs-frontend ${{ secrets.DOCKER_USERNAME }}/vuejs-frontend:latest
